### ISSUE TITLE
opkg update

### ISSUE THREAD

**Issue by lllaffer** [cokebar/openwrt-vlmcsd#14]
echo "src/gz announce http://cokebar.github.io/openwrt-vlmcsd/LEDE" >> /etc/opkg.conf
opkg update
opkg install vlmcsd

gives

root@oparch:~# opkg update
Downloading http://cokebar.github.io/openwrt-vlmcsd/LEDE/Packages.gz
*** Failed to download the package list from http://cokebar.github.io/openwrt-vlmcsd/LEDE/Packages.gz

Downloading http://downloads.lede-project.org/releases/17.01.4/targets/ar71xx/generic/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/reboot_core
Downloading http://downloads.lede-project.org/releases/17.01.4/targets/ar71xx/generic/packages/Packages.sig
Signature check passed.
Downloading http://downloads.lede-project.org/releases/17.01.4/packages/mips_24kc/base/Packages.gz
Updated list of available packages in /var/opkg-lists/reboot_base
Downloading http://downloads.lede-project.org/releases/17.01.4/packages/mips_24kc/base/Packages.sig
Signature check passed.
Downloading http://downloads.lede-project.org/releases/17.01.4/packages/mips_24kc/luci/Packages.gz
Updated list of available packages in /var/opkg-lists/reboot_luci
Downloading http://downloads.lede-project.org/releases/17.01.4/packages/mips_24kc/luci/Packages.sig
Signature check passed.
Downloading http://downloads.lede-project.org/releases/17.01.4/packages/mips_24kc/packages/Packages.gz
Updated list of available packages in /var/opkg-lists/reboot_packages
Downloading http://downloads.lede-project.org/releases/17.01.4/packages/mips_24kc/packages/Packages.sig
Signature check passed.
Downloading http://downloads.lede-project.org/releases/17.01.4/packages/mips_24kc/routing/Packages.gz
Updated list of available packages in /var/opkg-lists/reboot_routing
Downloading http://downloads.lede-project.org/releases/17.01.4/packages/mips_24kc/routing/Packages.sig
Signature check passed.
Downloading http://downloads.lede-project.org/releases/17.01.4/packages/mips_24kc/telephony/Packages.gz
Updated list of available packages in /var/opkg-lists/reboot_telephony
Downloading http://downloads.lede-project.org/releases/17.01.4/packages/mips_24kc/telephony/Packages.sig
Signature check passed.
Collected errors:
 * opkg_download: Failed to download http://cokebar.github.io/openwrt-vlmcsd/LEDE/Packages.gz, wget returned 8.

...

https://cokebar.github.io/openwrt-vlmcsd/LEDE/

gives

echo "src/gz announce http://cokebar.github.io/openwrt-vlmcsd/LEDE" >> /etc/opkg.conf
opkg update
opkg install vlmcsd

Anyhow, thnx for you work

**Comment by cokebar** [comment]
First, please make sure you can directly download files from github on your router. You may need a proxy/vpn, because github maybe blocked by your ISP.

**Comment by lllaffer** [comment]
Hallo cokebar,

 

thank you for your attention.

 

First of all : I got it working by downloading the gtk, transferring it to the router and installation by hand.

 

Works like a charm –thnx again for your work.

 

The IP is certainly not blocked by my ISP; -

The problem seems to me, that link

 

“http://cokebar.github.io/openwrt-vlmcsd/LEDE" 

 

leads to text(!)

 

echo "src/gz announce http://cokebar.github.io/openwrt-vlmcsd/LEDE" >> /etc/opkg.conf

opkg update

opkg install vlmcsd

 

rather than to a folder with

 

                Packages.gz

 

Anyhow - it works.

 

lll

 

…  could you give me a hint where I can find the source of exactly your implementation  ?!

I would like to have a look and would try to compile it by myself – which I never have done before (for a router ;-)

 

 

Von: Cokebar Chi [mailto:notifications@github.com] 
Gesendet: Montag, 20. November 2017 10:45
An: cokebar/openwrt-vlmcsd
Cc: lllaffer; Author
Betreff: *** GMX Spamverdacht *** Re: [cokebar/openwrt-vlmcsd] opkg update (#14)

 

First, please make sure you can directly download files from github on your router. You may need a proxy/vpn, because github maybe blocked by your ISP.

**Comment by lllaffer** [comment]
Hallo cokebar,

 

thank you for your attention.

 

First of all : I got it working by downloading the gtk, transferring it to the router and installation by hand.

                                                                                              --- ipk of course

Works like a charm –thnx again for your work.

 

The IP is certainly not blocked by my ISP; -

The problem seems to me, that link

 

“http://cokebar.github.io/openwrt-vlmcsd/LEDE" 

 

leads to text(!)

 

echo "src/gz announce http://cokebar.github.io/openwrt-vlmcsd/LEDE" >> /etc/opkg.conf

opkg update

opkg install vlmcsd

 

rather than to a folder with

 

                Packages.gz

 

Anyhow - it works.

 

lll

 

…  could you give me a hint where I can find the source of exactly your implementation  ?!

I would like to have a look and would try to compile it by myself – which I never have done before (for a router ;-)

 

 

Von: Cokebar Chi [mailto:notifications@github.com] 
Gesendet: Montag, 20. November 2017 10:45
An: cokebar/openwrt-vlmcsd
Cc: lllaffer; Author
Betreff: *** GMX Spamverdacht *** Re: [cokebar/openwrt-vlmcsd] opkg update (#14)

 

First, please make sure you can directly download files from github on your router. You may need a proxy/vpn, because github maybe blocked by your ISP.

**Comment by cokebar** [comment]
This usage is limited by github. I cannot guarantee that it works.
