### ISSUE TITLE
Option in /etc/init.d/vlmcsd

### ISSUE THREAD

**Issue by Izumiko** [cokebar/openwrt-vlmcsd#15]
Could you add `-L [::]:1688` to /etc/init.d/vlmcsd (or delete `-L 0.0.0.0:1688` in it)? I want vlmcsd listening on both IPv4 and IPv6. And I also tried if the server didn't have an IPv6 address, vlmcsd wouldn't fail.

**Comment by cokebar** [comment]
19bef0fa953032c874fa26831b3f319681b30e47

**Comment by Izumiko** [comment]
Sorry, I didn't say it clearly. I mean use `/usr/bin/vlmcsd -i /etc/vlmcsd.ini -p /tmp/vlmcsd.pid -l syslog -L 0.0.0.0:1688 -L [::]:1688` or `/usr/bin/vlmcsd -i /etc/vlmcsd.ini -p /tmp/vlmcsd.pid -l syslog`.

with present  `/usr/bin/vlmcsd -i /etc/vlmcsd.ini -p /tmp/vlmcsd.pid -l syslog -L [::]:1688`, the results are:
```
D:\>vlmcs 10.133.38.38:1688
Connecting to 10.133.38.38:1688 ... 10.133.38.38:1688: 由于目标计算机积极拒绝，无法连接。
Fatal: Could not connect to any KMS server

D:\>vlmcs [2001:da8:203:f110:deef:9ff:xxxx:xxxx]:1688
Connecting to [2001:da8:203:f110:deef:9ff:xxxx:xxxx]:1688 ... successful
Sending activation request (KMS V6) 1 of 1  -> 06401-03858-000-414100-03-1066-9600.0000-0692018 (3A1C049600B60076)
```

**Comment by cokebar** [comment]
bae28a5fa06a17247e4aeff2e9b4fd029f5c9547

**Comment by daiaji** [comment]
@cokebar 这属实很怪
https://github.com/nodejs/node/issues/9390
按这个说法
[::]这是一个双栈地址……
所有的平台都一样……
为什么会这样……
vlmcsd的实现还是有问题吧……
