### ISSUE TITLE
get error while builting in openwrt master

### ISSUE THREAD

**Issue by jack338c** [cokebar/openwrt-vlmcsd#16]
lede1701 is ok

here are the error logs,thank you

jack@jack-R478-R429:~/openwrtfp$ make package/feeds/openwrt-vlmcsd/compile V=s
make[2]: Entering directory '/home/jack/openwrtfp/scripts/config'
make[2]: Leaving directory '/home/jack/openwrtfp/scripts/config'
time: target/linux/prereq#0.18#0.08#0.25
make[1]: Entering directory '/home/jack/openwrtfp'
make[2]: Entering directory '/home/jack/openwrtfp/package/libs/toolchain'
echo "libc" >> /home/jack/openwrtfp/staging_dir/target-mips_24kc_musl/pkginfo/toolchain.default.install
echo "libgcc" >> /home/jack/openwrtfp/staging_dir/target-mips_24kc_musl/pkginfo/toolchain.default.install
echo "libstdcpp" >> /home/jack/openwrtfp/staging_dir/target-mips_24kc_musl/pkginfo/toolchain.default.install
echo "libpthread" >> /home/jack/openwrtfp/staging_dir/target-mips_24kc_musl/pkginfo/toolchain.default.install
echo "librt" >> /home/jack/openwrtfp/staging_dir/target-mips_24kc_musl/pkginfo/toolchain.default.install
make[2]: Leaving directory '/home/jack/openwrtfp/package/libs/toolchain'
time: package/libs/toolchain/compile#0.22#0.10#0.32
make[2]: Entering directory '/home/jack/openwrtfp/package/feeds/openwrt-vlmcsd'
mkdir -p /home/jack/openwrtfp/dl
SHELL= flock /home/jack/openwrtfp/tmp/.svn1111.tar.gz.flock -c '  	/home/jack/openwrtfp/scripts/download.pl "/home/jack/openwrtfp/dl" "svn1111.tar.gz" "x" "" "https://github.com/cokebar/vlmcsd/archive"    '
Cannot find appropriate hash command, ensure the provided hash is either a MD5 or SHA256 checksum.
Makefile:44: recipe for target '/home/jack/openwrtfp/dl/svn1111.tar.gz' failed
make[2]: *** [/home/jack/openwrtfp/dl/svn1111.tar.gz] Error 255
make[2]: Leaving directory '/home/jack/openwrtfp/package/feeds/openwrt-vlmcsd'
Command exited with non-zero status 2
time: package/feeds/openwrt-vlmcsd/compile#0.20#0.08#0.28
package/Makefile:107: recipe for target 'package/feeds/openwrt-vlmcsd/compile' failed
make[1]: *** [package/feeds/openwrt-vlmcsd/compile] Error 2
make[1]: Leaving directory '/home/jack/openwrtfp'
/home/jack/openwrtfp/include/toplevel.mk:216: recipe for target 'package/feeds/openwrt-vlmcsd/compile' failed
make: *** [package/feeds/openwrt-vlmcsd/compile] Error 2

**Comment by cokebar** [comment]
#17

**Comment by jack338c** [comment]
@cokebar 
thanks for your help
