### ISSUE TITLE
Consider providing a md5 or sha1 hash

### ISSUE THREAD

**Issue by OrcaXS** [cokebar/openwrt-vlmcsd#17]
When compiling in Openwrt source code, make complained `
Cannot find appropriate hash command, ensure the provided hash is either a MD5 or SHA256 checksum.` and stopped.
After adding `PKG_MD5SUM=806b26fcb3973e4f4384da2e0c56d3d1` (the md5sum of `https://github.com/cokebar/vlmcsd/archive/svn1111.tar.gz`) to Makefile it went fine.

**Comment by cokebar** [comment]
cde6d4305e7de10f5c47cb936a3b2559e69fb96c
