### ISSUE TITLE
can you release for bcm2835 rasberry ,thankyou very mach.

### ISSUE THREAD

**Issue by moroseboy** [cokebar/openwrt-vlmcsd#20]
can you release for bcm2835 rasberry ,thankyou very mach.

**Comment by moroseboy** [comment]
> can you release for bcm2835 rasberry ,thankyou very mach.

I  successfully compile VLMCSD for my raspberry B,THANK YOU .

**Comment by cokebar** [comment]
f4355241225b1656140ee995728d537fda771bf8
