### ISSUE TITLE
Malformed package file

### ISSUE THREAD

**Issue by clu66er** [cokebar/openwrt-vlmcsd#28]
Hello there and thanks for your project in advance!

root@OpenWrt:~# cat /etc/openwrt_release
DISTRIB_ID='OpenWrt'
DISTRIB_RELEASE='19.07.7'
DISTRIB_REVISION='r11306-c4a6851c72'
DISTRIB_TARGET='ramips/mt76x8'
DISTRIB_ARCH='mipsel_24kc'
DISTRIB_DESCRIPTION='OpenWrt 19.07.7 r11306-c4a6851c72'
DISTRIB_TAINTS=''

Just tried to install vlmcsd, but got an error message:

root@OpenWrt:~# opkg install vlmcsd_svn1113-1_mipsel_24kc.ipk
Collected errors:
 * pkg_init_from_file: Malformed package file vlmcsd_svn1113-1_mipsel_24kc.ipk.

I found some links with the same trouble, hope it helps:  
https://opkg-devel.narkive.com/UHFxyzdg/1st-attempt-at-building-package-malformed-package-file-package-opk
https://github.com/pyrovski/wrtbwmon/issues/22

Could you fix it, please?
Best regards!

**Comment by cokebar** [comment]
This repo's pre-compiled ipks do not support Openwrt 19.
Sorry about that but I have no time to keep this repo up-to-date.
Please git clone this repo to your own PC and use the newest Openwrt SDK to compile it by  your self.
