### ISSUE TITLE
missing openwrt release key

### ISSUE THREAD

**Issue by KyonLi** [cokebar/openwrt-vlmcsd#9]
root@OpenWrt:/etc/opkg# opkg update
Downloading http://cokebar.github.io/openwrt-vlmcsd/OpenWrt/Packages.gz.
Updated list of available packages in /var/opkg-lists/announce.
Downloading http://cokebar.github.io/openwrt-vlmcsd/OpenWrt/Packages.sig.
Signature check failed.
Remove wrong Signature file.
Collected errors:
 * opkg_download: Failed to download http://cokebar.github.io/openwrt-vlmcsd/OpenWrt/Packages.sig, wget returned 8.

**Comment by cokebar** [comment]
打开Luci，定位到“系统”-“软件包”-“配置”选项卡，然后在设置中现将下面一行注释掉：
#option check_signature 1
(PS: 1改成0貌似不行，必须注释掉或者删掉)
